#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import shutil
from conans import ConanFile, CMake, tools


class GstreamerBuildToolsConan(ConanFile):
    name = "gstreamer-build-tools"
    version = "1.14.0.1"
    description = "cerbero build tools generated by boostrap"
    url = "https://github.com/yjjnls/conan-gstreamer"
    license = "Apache-2.0"
    homepage = "https://github.com/yjjnls/conan-gstreamer"
    settings = "os", "arch", "compiler", "build_type"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = "shared=True", "fPIC=True"
    source_subfolder = "source_subfolder"
    root = ""

    def config_options(self):
        self.root = "%s/.." % os.getcwd()
        if self.settings.os == "Windows":
            self.options.remove("fPIC")

    def system_requirements(self):
        self.run(
            "if [ ! -d cerbero ]; then git clone https://github.com/yjjnls/cerbero; fi",
            cwd=self.root)

    def build(self):
        if self.settings.os == "Linux":
            self.run(
                "sudo ./cerbero-uninstalled -c config/linux.config bootstrap",
                cwd="%s/cerbero" % self.root)

    def package(self):
        self.copy(pattern="*", dst="build", src="%s/cerbero/build" % self.root)
